# Per-request credit-based MoE expert routing (request-local load balancing).
# Ported from the offline simulator in eval/sim_credit.py. Gated to the qwen3.5-moe
# model and enabled by SGLANG_CREDIT_ROUTER; a no-op for every other model / when off.
#
# Idea: every request holds an int credit balance per (layer, expert), initialized to
# max_cred and regenerated by +1 each decode step (each layer is visited once per step,
# so per-layer == per-step). Selecting an expert for a token costs `cost` credits. A
# rank-slot threshold forces low-credit (recently hot) experts out of the lower-priority
# top-k slots, so a single request cannot keep concentrating load on the same experts.

import logging
from typing import TYPE_CHECKING, Callable, Optional

import torch

from sglang.srt.environ import envs
from sglang.srt.layers.moe.topk import TopKOutputChecker
from sglang.srt.state_capturer.credit import get_global_credit_capturer

if TYPE_CHECKING:
    from sglang.srt.configs.model_config import ModelConfig
    from sglang.srt.model_executor.forward_batch_info import ForwardBatch

logger = logging.getLogger(__name__)

# Fixed number of exclusion passes. The simulator loops until no selected expert fails
# its rank threshold; a data-dependent loop cannot be CUDA-graph captured, so we run a
# fixed count instead (passes after convergence are a no-op). Calibrate to the max
# passes observed in eval/sim_credit.py for the chosen (max_cred, cost).
CREDIT_MAX_PASSES = 8


class CreditRouter:
    @staticmethod
    def create(
        *,
        model_config: "ModelConfig",
        max_running_requests: int,
        device: str,
    ) -> Optional["CreditRouter"]:
        if not envs.SGLANG_CREDIT_ROUTER.get():
            return None
        tc = model_config.hf_text_config
        if tc.model_type != "qwen3_5_moe_text":
            raise ValueError(
                "SGLANG_CREDIT_ROUTER is set but the model is not qwen3_5_moe; "
                "credit routing disabled."
            )
        router = CreditRouter(
            num_layers=tc.num_hidden_layers,
            num_experts=tc.num_experts,
            top_k=tc.num_experts_per_tok,
            max_running_requests=max_running_requests,
            max_cred=envs.SGLANG_CREDIT_MAX_CRED.get(),
            cost=envs.SGLANG_CREDIT_COST.get(),
            device=device,
        )
        logger.info(
            "CreditRouter enabled: layers=%d experts=%d k=%d max_cred=%d cost=%d "
            "thresh=%s passes=%d",
            tc.num_hidden_layers,
            tc.num_experts,
            tc.num_experts_per_tok,
            router.max_cred,
            router.cost,
            router.thresh.view(-1).tolist(),
            CREDIT_MAX_PASSES,
        )
        return router

    def __init__(
        self,
        *,
        num_layers: int,
        num_experts: int,
        top_k: int,
        max_running_requests: int,
        max_cred: int,
        cost: int,
        device: str,
    ):
        self.num_experts = num_experts
        self.top_k = top_k
        self.max_cred = max_cred
        self.cost = cost
        # One reserved sink row so padded (phantom) tokens under CUDA-graph replay
        # can never touch a live request's credit state.
        self.pad_slot = max_running_requests
        self.creds = torch.full(
            (max_running_requests + 1, num_layers, num_experts),
            max_cred,
            dtype=torch.int32,
            device=device,
        )
        # Device-side max_cred row for the prefill reset: assigning a Python scalar to a
        # CUDA slice is an illegal CPU->CUDA copy during CUDA-graph capture, so we keep a
        # preallocated on-device value to broadcast instead.
        self.max_cred_row = torch.full(
            (num_experts,), max_cred, dtype=torch.int32, device=device
        )
        # Rank-slot barrier: the i-th selected expert must hold >= (i-1)*step credits
        # (shifted down one slot vs the simulator's i*step, then floored at 0, so the
        # top-2 slots are always unconstrained).
        # Layer-independent, broadcast over the batch -> shape [1, k].
        step = max_cred // top_k
        self.thresh = (
            ((torch.arange(top_k, device=device)) * step)
            .clamp(min=0, max=max_cred-1)
            .view(1, top_k)
        )
        # Optional debug counters (SGLANG_CREDIT_DEBUG): accumulated on-device INSIDE the
        # captured graph and flushed per forward, so they reflect what actually happens at
        # replay. Layout: [decode_layer_calls, reset_layer_calls, credits_spent, replaced].
        # [decode_layer_calls, reset_layer_calls, credits_spent, replaced, total_rows, valid_rows]
        self.debug = envs.SGLANG_CREDIT_DEBUG.get()
        self._dbg = torch.zeros(6, dtype=torch.int64, device=device) if self.debug else None
        self._dbg_totals = [0, 0, 0, 0, 0, 0]
        self._dbg_steps = 0

    def route(
        self,
        *,
        layer_id: int,
        hidden_states: torch.Tensor,
        router_logits: torch.Tensor,
        forward_batch: "ForwardBatch",
        vanilla_topk: Callable,
    ):
        # Always compute the vanilla output: it fixes the correct output format/dtypes
        # for the downstream expert kernels, and is the prefill / fallback path.
        topk_output = vanilla_topk(hidden_states, router_logits)
        idx = forward_batch.req_pool_indices.long()  # [B]; decode: row i == request i

        if not forward_batch.forward_mode.is_decode():
            # Prefill/extend: route vanilla and (re)initialize this layer's credit rows to
            # max_cred so decode starts fresh (idempotent across prefill chunks). Gated to
            # extend so idle/verify batches don't touch state.
            # NOTE: under a padded extend CUDA graph on single GPU the ZERO-padded tail
            # (req_pool_indices == 0) can also reset pool-slot-0's credits -- bounded to one
            # slot and benign (reset toward max), unlike the depleting decode path.
            if forward_batch.forward_mode.is_extend():
                self.creds[idx, layer_id, :] = self.max_cred_row
                if self.debug:
                    self._dbg[1] += 1
            return topk_output

        if not TopKOutputChecker.format_is_standard(topk_output):
            # Unexpected MoE backend (bypassed / triton-kernels); leave vanilla untouched.
            return topk_output
        if router_logits.shape[0] != idx.shape[0]:
            # Not the plain one-token-per-request decode layout; stay safe.
            return topk_output

        return self._route_decode(layer_id, router_logits, idx, forward_batch, topk_output)

    def _route_decode(self, layer_id, router_logits, idx, forward_batch, template):
        B = router_logits.shape[0]
        device = router_logits.device

        # Real vs padded rows. Prefer the explicit non-padded count (only populated when
        # moe_ep_size > 1). Otherwise DO NOT mask from forward_batch scalar-array fields:
        # empirically, both `positions` and `seq_lens` read as their padded/fill values for
        # real rows in this hybrid-mamba model's decode CUDA graph (they are not refreshed
        # the way attention's own buffers are), which silently dropped ~99% of real rows and
        # made credit routing a no-op. All-True is correct for the common single-GPU case:
        # the decode batch is padded only up to the next captured graph size (~1 padded row
        # at bs 127->128), so the residual pool-slot-0 artifact from those few padded rows
        # (all req_pool_indices == 0) is negligible.
        ntn = forward_batch.num_token_non_padded
        if ntn is not None:
            valid = torch.arange(B, device=device) < ntn  # [B] bool
        else:
            valid = torch.ones(B, dtype=torch.bool, device=device)
        valid_i = valid.view(B, 1).to(torch.int32)
        safe_idx = torch.where(valid, idx, torch.full_like(idx, self.pad_slot))

        scores = torch.softmax(router_logits.float(), dim=-1)  # [B, E]

        # Regenerate: +1 credit for real rows, clamped at max_cred.
        creds = torch.clamp(self.creds[safe_idx, layer_id, :] + valid_i, max=self.max_cred)

        # Iterative exclusion, fixed pass count (CUDA-graph safe: no host sync / branch).
        excluded = torch.zeros(B, self.num_experts, dtype=torch.bool, device=device)
        neg_inf = torch.finfo(scores.dtype).min
        topk_scores = ids = None
        for _ in range(CREDIT_MAX_PASSES):
            # masked_fill takes a Python scalar and fills on-device (CUDA-graph safe);
            # torch.where(excluded, neg_inf, scores) would materialize a CPU scalar tensor.
            biased = scores.masked_fill(excluded, neg_inf)
            topk_scores, ids = torch.topk(biased, self.top_k, dim=-1)  # [B, k]
            fail = torch.gather(creds, 1, ids) < self.thresh  # [B, k]
            excluded = excluded.scatter(1, ids, fail)  # ids unique per row

        # Renormalized routing weights over the final selection.
        weights = topk_scores / topk_scores.sum(dim=-1, keepdim=True)

        # Spend: subtract cost from the finally-selected experts (real rows only), >= 0.
        spend = torch.zeros_like(creds).scatter_(
            1, ids, (self.cost * valid_i).expand(-1, self.top_k)
        )
        self.creds[safe_idx, layer_id, :] = torch.clamp(creds - spend, min=0)

        cap = get_global_credit_capturer()
        if cap is not None:
            # Post-credit ids + the credit each selected expert held at decision time
            # (post-regen, pre-spend). int16: expert ids and credits both fit.
            sel_creds = torch.gather(creds, 1, ids)  # [B, k]
            rec = torch.cat([ids.to(torch.int16), sel_creds.to(torch.int16)], dim=1)
            cap.capture(layer_id, rec)  # [B, 2k]

        if self.debug:
            changed = (ids.long() != template.topk_ids.long()).any(dim=-1) & valid  # [B]
            self._dbg[0] += 1
            self._dbg[2] += spend.sum()
            self._dbg[3] += changed.sum()
            self._dbg[4] += B
            self._dbg[5] += valid_i.sum()

        return template._replace(
            topk_weights=weights.to(template.topk_weights.dtype),
            topk_ids=ids.to(template.topk_ids.dtype),
        )

    def debug_flush(self):
        """Read + zero the on-device debug counters (host sync; call outside the graph)."""
        if not self.debug:
            return
        d = self._dbg.tolist()
        self._dbg.zero_()
        for i in range(4):
            self._dbg_totals[i] += d[i]
        self._dbg_steps += 1
        if self._dbg_steps % 50 == 0:
            t = self._dbg_totals
            calls = max(t[0], 1)
            logger.info(
                "[credit-debug] %d forwards: decode_layer_calls=%d reset_layer_calls=%d "
                "credits_spent=%d replaced=%d | per_decode_call: rows=%.1f valid=%.1f "
                "replaced=%.1f",
                self._dbg_steps, t[0], t[1], t[2], t[3],
                t[4] / calls, t[5] / calls, t[3] / calls,
            )


def get_global_credit_router() -> Optional["CreditRouter"]:
    from sglang.srt.runtime_context import get_resources

    return get_resources().credit_router


def set_global_credit_router(router: Optional["CreditRouter"]):
    from sglang.srt.runtime_context import get_resources

    get_resources().credit_router = router
