# Per-request credit-based MoE expert routing (request-local load balancing).
# Ported from the offline simulator in eval/sim_credit.py. Gated to the qwen3.5-moe
# model and enabled by SGLANG_CREDIT_ROUTER; a no-op for every other model / when off.
#
# Idea: every request holds an int credit balance per (layer, expert), initialized to
# max_cred and regenerated by +1 each decode step (each layer is visited once per step,
# so per-layer == per-step). Selecting an expert for a token costs `cost` credits.
# Selection adds a soft credit bias to the gate scores before top-k:
#     topk(scores + beta * creds/creds_rowmax * scores_rowmax)
# so low-credit (recently hot) experts sink in the ranking and drop out at near-ties,
# while high-margin picks survive. Routing weights are renormalized from the ORIGINAL
# scores of the selected experts, so a flip never imports the biased score.

import logging
from typing import TYPE_CHECKING, Callable, Optional

import torch

from sglang.srt.environ import envs
from sglang.srt.layers.moe.topk import TopKOutputChecker
from sglang.srt.model_executor.forward_batch_info import enable_num_token_non_padded
from sglang.srt.state_capturer.credit import get_global_credit_capturer

if TYPE_CHECKING:
    from sglang.srt.configs.model_config import ModelConfig
    from sglang.srt.model_executor.forward_batch_info import ForwardBatch

logger = logging.getLogger(__name__)


class CreditRouter:
    @staticmethod
    def create(
        *,
        model_config: "ModelConfig",
        max_running_requests: int,
        device: str,
    ) -> Optional["CreditRouter"]:
        if not envs.SGLANG_CREDIT_ROUTER.get():
            return None
        if envs.SGLANG_CAI_ROUTER.get():
            raise ValueError(
                "SGLANG_CREDIT_ROUTER and SGLANG_CAI_ROUTER are mutually exclusive."
            )
        tc = model_config.hf_text_config
        if tc.model_type != "qwen3_5_moe_text":
            raise ValueError(
                "SGLANG_CREDIT_ROUTER is set but the model is not qwen3_5_moe; "
                "credit routing disabled."
            )
        router = CreditRouter(
            num_layers=tc.num_hidden_layers,
            num_experts=tc.num_experts,
            top_k=tc.num_experts_per_tok,
            max_running_requests=max_running_requests,
            max_cred=envs.SGLANG_CREDIT_MAX_CRED.get(),
            cost=envs.SGLANG_CREDIT_COST.get(),
            beta=envs.SGLANG_CREDIT_BETA.get(),
            device=device,
        )
        logger.info(
            "CreditRouter enabled: layers=%d experts=%d k=%d max_cred=%d cost=%d "
            "beta=%s",
            tc.num_hidden_layers,
            tc.num_experts,
            tc.num_experts_per_tok,
            router.max_cred,
            router.cost,
            router.beta,
        )
        return router

    def __init__(
        self,
        *,
        num_layers: int,
        num_experts: int,
        top_k: int,
        max_running_requests: int,
        max_cred: int,
        cost: int,
        beta: float,
        device: str,
    ):
        self.num_experts = num_experts
        self.top_k = top_k
        self.max_cred = max_cred
        self.cost = cost
        self.beta = beta
        # One reserved sink row so padded (phantom) tokens under CUDA-graph replay
        # can never touch a live request's credit state.
        self.pad_slot = max_running_requests
        self.creds = torch.full(
            (max_running_requests + 1, num_layers, num_experts),
            max_cred,
            dtype=torch.int32,
            device=device,
        )
        # Device-side max_cred row for the prefill reset: assigning a Python scalar to a
        # CUDA slice is an illegal CPU->CUDA copy during CUDA-graph capture, so we keep a
        # preallocated on-device value to broadcast instead.
        self.max_cred_row = torch.full(
            (num_experts,), max_cred, dtype=torch.int32, device=device
        )
        # Live (un-padded) row count for the padding mask: written eagerly by
        # on_forward_start before every forward, read inside the captured graph.
        # forward_batch.num_token_non_padded cannot serve this purpose on single GPU:
        # the decode graph runner attaches its static buffer to the captured batch
        # unconditionally, but the buffer registry refreshes it per replay only when
        # moe_ep_size > 1, so at replay it holds the LAST captured shape's size (= 1,
        # capture runs largest-to-smallest) and would mask out almost every real row.
        # Initialized to 0 so capture/warmup dummy forwards mask every row and leave
        # the credit state untouched.
        self._num_valid = torch.zeros(1, dtype=torch.int32, device=device)
        # With moe_ep_size > 1 the num_token_non_padded slot IS registry-refreshed
        # (and counts the DP-gathered token layout, which _num_valid does not), so
        # prefer it there. Python constant -> capture-stable branch.
        self.use_ntn = enable_num_token_non_padded()
        # Optional debug counters (SGLANG_CREDIT_DEBUG): accumulated on-device INSIDE the
        # captured graph and flushed per forward, so they reflect what actually happens at
        # replay. Layout: [decode_layer_calls, reset_layer_calls, credits_spent, replaced].
        # [decode_layer_calls, reset_layer_calls, credits_spent, replaced, total_rows, valid_rows]
        self.debug = envs.SGLANG_CREDIT_DEBUG.get()
        self._dbg = torch.zeros(6, dtype=torch.int64, device=device) if self.debug else None
        self._dbg_totals = [0, 0, 0, 0, 0, 0]
        self._dbg_steps = 0

    def on_forward_start(self, *, forward_batch: "ForwardBatch") -> None:
        """Record the live (un-padded) batch size for the in-graph padding mask.

        Called eagerly (outside any CUDA graph) before every forward, so a graph
        replay reads this step's real row count. IDLE batches have batch_size 0,
        which masks every row: a replayed decode graph then touches no state, matching
        the eager IDLE no-op.
        """
        self._num_valid.fill_(forward_batch.batch_size)

    def route(
        self,
        *,
        layer_id: int,
        hidden_states: torch.Tensor,
        router_logits: torch.Tensor,
        forward_batch: "ForwardBatch",
        vanilla_topk: Callable,
    ):
        # Always compute the vanilla output: it fixes the correct output format/dtypes
        # for the downstream expert kernels, and is the prefill / fallback path.
        topk_output = vanilla_topk(hidden_states, router_logits)
        idx = forward_batch.req_pool_indices.long()  # [B]; decode: row i == request i

        if not forward_batch.forward_mode.is_decode():
            # Prefill/extend: route vanilla and (re)initialize this layer's credit rows to
            # max_cred so decode starts fresh (idempotent across prefill chunks). Gated to
            # extend so idle/verify batches don't touch state. Padded rows (only present
            # under a padded extend CUDA graph or its capture) are redirected to the
            # pad_slot sink so they can never reset a live request's credits.
            if forward_batch.forward_mode.is_extend():
                valid = torch.arange(idx.shape[0], device=idx.device) < self._num_valid
                safe_idx = torch.where(valid, idx, torch.full_like(idx, self.pad_slot))
                self.creds[safe_idx, layer_id, :] = self.max_cred_row
                if self.debug:
                    self._dbg[1] += 1
            return topk_output

        if not TopKOutputChecker.format_is_standard(topk_output):
            # Unexpected MoE backend (bypassed / triton-kernels); leave vanilla untouched.
            return topk_output
        if router_logits.shape[0] != idx.shape[0]:
            # Not the plain one-token-per-request decode layout; stay safe.
            return topk_output

        return self._route_decode(layer_id, router_logits, idx, forward_batch, topk_output)

    def _route_decode(self, layer_id, router_logits, idx, forward_batch, template):
        B = router_logits.shape[0]
        device = router_logits.device

        # Real vs padded rows. Only when moe_ep_size > 1 is num_token_non_padded a
        # registry-refreshed graph slot that is safe to read in-graph. On single GPU
        # the captured batch still carries the buffer, but nothing refreshes it at
        # replay -- it permanently holds the LAST captured shape's size (1), which
        # silently dropped ~99% of real rows and made credit routing a no-op under
        # CUDA graphs (this, not stale positions/seq_lens, was the root cause; both
        # of those ARE refreshed per replay in this tree). Use the router-owned
        # _num_valid instead: written eagerly before every forward, so padded tail
        # rows (req_pool_indices == 0) are diverted to the pad_slot sink and pool
        # slot 0's live credits are never touched.
        ntn = forward_batch.num_token_non_padded
        if self.use_ntn and ntn is not None:
            valid = torch.arange(B, device=device) < ntn  # [B] bool
        else:
            valid = torch.arange(B, device=device) < self._num_valid  # [B] bool
        valid_i = valid.view(B, 1).to(torch.int32)
        safe_idx = torch.where(valid, idx, torch.full_like(idx, self.pad_slot))

        scores = torch.softmax(router_logits.float(), dim=-1)  # [B, E]

        # Regenerate: +1 credit for real rows, clamped at max_cred.
        creds = torch.clamp(self.creds[safe_idx, layer_id, :] + valid_i, max=self.max_cred)

        # Soft credit bias (mirrors eval/sim_credit.py select_expert_credit):
        # rank by scores + beta * creds/creds_rowmax * scores_rowmax. The rowmax
        # denominator is clamped to 1 so a fully-drained row can't divide by zero
        # (creds are ints >= 0; rowmax is max_cred in practice). All ops use Python
        # scalars only via clamp/mul, so this is CUDA-graph safe.
        cred_bias = (
            creds.float()
            / creds.max(dim=-1, keepdim=True)[0].clamp(min=1)
            * scores.max(dim=-1, keepdim=True)[0]
        )
        _, ids = torch.topk(scores + self.beta * cred_bias, self.top_k, dim=-1)  # [B, k]

        # Routing weights renormalized from the ORIGINAL scores of the selection.
        topk_scores = torch.gather(scores, 1, ids)  # [B, k]
        weights = topk_scores / topk_scores.sum(dim=-1, keepdim=True)

        # Spend: subtract cost from the finally-selected experts (real rows only), >= 0.
        spend = torch.zeros_like(creds).scatter_(
            1, ids, (self.cost * valid_i).expand(-1, self.top_k)
        )
        self.creds[safe_idx, layer_id, :] = torch.clamp(creds - spend, min=0)

        cap = get_global_credit_capturer()
        if cap is not None:
            # Post-credit ids + the credit each selected expert held at decision time
            # (post-regen, pre-spend). int16: expert ids and credits both fit.
            sel_creds = torch.gather(creds, 1, ids)  # [B, k]
            rec = torch.cat([ids.to(torch.int16), sel_creds.to(torch.int16)], dim=1)
            cap.capture(layer_id, rec)  # [B, 2k]

        if self.debug:
            changed = (ids.long() != template.topk_ids.long()).any(dim=-1) & valid  # [B]
            self._dbg[0] += 1
            self._dbg[2] += spend.sum()
            self._dbg[3] += changed.sum()
            self._dbg[4] += B
            self._dbg[5] += valid_i.sum()

        return template._replace(
            topk_weights=weights.to(template.topk_weights.dtype),
            topk_ids=ids.to(template.topk_ids.dtype),
        )

    def debug_flush(self):
        """Read + zero the on-device debug counters (host sync; call outside the graph)."""
        if not self.debug:
            return
        d = self._dbg.tolist()
        self._dbg.zero_()
        for i in range(4):
            self._dbg_totals[i] += d[i]
        self._dbg_steps += 1
        if self._dbg_steps % 50 == 0:
            t = self._dbg_totals
            calls = max(t[0], 1)
            logger.info(
                "[credit-debug] %d forwards: decode_layer_calls=%d reset_layer_calls=%d "
                "credits_spent=%d replaced=%d | per_decode_call: rows=%.1f valid=%.1f "
                "replaced=%.1f",
                self._dbg_steps, t[0], t[1], t[2], t[3],
                t[4] / calls, t[5] / calls, t[3] / calls,
            )


def get_global_credit_router() -> Optional["CreditRouter"]:
    from sglang.srt.runtime_context import get_resources

    return get_resources().credit_router


def set_global_credit_router(router: Optional["CreditRouter"]):
    from sglang.srt.runtime_context import get_resources

    get_resources().credit_router = router
